# --- !Ups

create table "pklikestats" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "likes" int not null,
  "dislikes" int not null
);

# --- !Downs

drop table "pklikestats" if exists;
